services:
  bot:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data
    ports:
      - "127.0.0.1:8000:8000"
      - "100.123.144.123:8000:8000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
